### ISSUE TITLE
Setting color from layer data

### ISSUE THREAD

**Issue by dlau** [tilemill-project/tilemill#1809]
I'm having an issue setting a polygon fill color from a data source.

I have tried the following:
polygon-fill: #[base_colorcode];

With the following example of types of base_colorcodes values encoded in geojson --types confirmed by hovering in the feature viewer:
"#36de6e" --string
"36de6e" --string
3595886 -- number

From: https://github.com/nvkelso/carto-css-map-styling/blob/master/4_EXTREMELY_ADVANCED_BITS.md

I have also tried creating three new properties, "r, g, and b" with the values as numbers, using it like this:
polygon-fill: rgb([r],[g],[b]);

In every case tilemill throws an error. Can anyone suggest a way to store and retrieve colors in a layer's data source?

**Comment by Tybion** [comment]
Hello, Dane.
I have installed Tilemill 10.2 on Ubuntu 14.04 like so ..
sudo -E add-apt-repository ppa:developmentseed/mapbox
sudo -E apt-get update
sudo -E apt-get install tilemill libmapnik nodejs

The line 'polygon-fill: [rgb];' reports 'Failed to parse color: "[rgb]" in style 'geology15mv' in PolygonSymbolizer'
The 'rgb' field is varchar(7) and has values like '#CCB3CC'

Can I make this work in 10.2 or do I need to build Tilemill from source code?

**Comment by Tybion** [comment]
@springmeyer 
In anticipation, I downloaded tilemill-master.zip and ran 'npm install' but I get these errors ..

<pre>
npm http GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/nan

> mapnik@3.1.6 install /home/linux/tilemill/node_modules/mapnik
> node-pre-gyp install --fallback-to-build

node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/mapnik/v3.1.6/node-v11-linux-ia32.tar.gz
node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/mapnik/v3.1.6/node-v11-linux-ia32.tar.gz
node-pre-gyp http 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/mapnik/v3.1.6/node-v11-linux-ia32.tar.gz (falling back to source compile with node-gyp) 
make: Entering directory /home/linux/tilemill/node_modules/mapnik/build
  ACTION binding_gyp_action_before_build_target_generate_protoc_files Release/obj/gen/vector_tile.pb.cc
  ACTION binding_gyp_action_before_build_target_generate_setting Release/obj/gen/mapnik_settings.js
  COPY /home/linux/tilemill/node_modules/mapnik/lib/binding/node-v11-linux-ia32/mapnik_settings.js
  TOUCH Release/obj.target/action_before_build.stamp
  CXX(target) Release/obj.target/mapnik/src/json_proj_transform_grammar.o
../src/json_proj_transform_grammar.cpp:1:59: fatal error: mapnik/json/geometry_generator_grammar_impl.hpp: No such file or directory
 #include <mapnik/json/geometry_generator_grammar_impl.hpp>
                                                           ^
compilation terminated.
</pre>

**Comment by Tybion** [comment]
An update - I have now successfully installed the development version of TileMill on a fresh install of Linux Mint 17 (ie. Ubuntu 14.04) using mostly the instructions at https://www.mapbox.com/tilemill/docs/source/
<pre>
Preparation ..
sudo apt-get install build-essential libwebkit-dev
sudo add-apt-repository ppa:developmentseed/mapbox
sudo apt-get update

# I then used Synaptic to force an install of the older nodejs from the PPA, then ..
sudo apt-get install libmapnik libmapnik-dev mapnik-utils nodejs-dev npm

# install very latest version of tilemill ..
git clone https://github.com/mapbox/tilemill.git
cd tilemill
git checkout master
npm install

# then run tilemill
./index.js
</pre>

'polygon-fill: [rgb];' works nicely with this version - thanks Dane.

FYI, when I export to an MBTiles file, the status bar does not update, and eventually there is a message about the export failing, but it seems that the export probably does work.
