### ISSUE TITLE
Installation not working on Ubuntu 10.10

### ISSUE THREAD

**Issue by Matsglobetrotter** [tilemill-project/tilemill#282]
Hi, 

I am not a regular Ubuntu user but loved what tilemill can do so have installed Ubunutu 10.10 just for that purpose. I have installed as per all instructions Mapnik and tilemill and it responds when doing the tests. But then it cant start. I have not changed any Path nor PythonPath nor changed anything in Settings.js as I would not know how to. what am I doing wrong? I have  a clean and fully updated Ubuntu.  

Regards,
## Mats

mats@ubuntu:~$ cd tilemill
mats@ubuntu:~/tilemill$ ./tilemill.js

node.js:63
    throw e;
    ^
Error: Cannot find module 'mapnik'
    at loadModule (node.js:275:15)
    at require (node.js:411:14)
    at Object.<anonymous> (/home/mats/tilemill/server/api.js:3:14)
    at Module._compile (node.js:462:23)
    at Module._loadScriptSync (node.js:469:10)
    at Module.loadSync (node.js:338:12)
    at loadModule (node.js:283:14)
    at require (node.js:411:14)
    at Object.<anonymous> (/home/mats/tilemill/tilemill.js:61:1)
    at Module._compile (node.js:462:23)
mats@ubuntu:~/tilemill$ 

the tests for mapnik is shown below

mats@ubuntu:~$ cd mapnik
mats@ubuntu:~/mapnik$ python tests/run_tests.py
- mapnik path: /usr/lib/python2.6/dist-packages/mapnik/**init**.py
- _mapnik.so path: /usr/lib/python2.6/dist-packages/mapnik/_mapnik.so
- Input plugins path: /usr/local/lib/mapnik/input
- Font path: /usr/share/fonts
- Running nosetests:

python_tests.cairo_test.test_pycairo_svg_surface ... ok
python_tests.datasource_test.test_field_listing ... ok
python_tests.datasource_test.test_total_feature_count ... ok
python_tests.datasource_test.test_feature_envelope ... ok
python_tests.datasource_test.test_feature_attributes ... ok
python_tests.filter_test.test_filter_init ... ok
python_tests.introspection_test.test_introspect_symbolizers ... TODO: need to expose symbolizer instances
python_tests.load_map_test.test_broken_files('../data/broken_maps/point_symbolizer_broken.xml',) ... ok
python_tests.load_map_test.test_broken_files('../data/broken_maps/db_user_broken.xml',) ... ok
python_tests.load_map_test.test_broken_files('../data/broken_maps/color_value_broken.xml',) ... ok
python_tests.load_map_test.test_broken_files('../data/broken_maps/stroke_dasharray_broken.xml',) ... ok
python_tests.load_map_test.test_broken_files('../data/broken_maps/datasource_type_missing.xml',) ... ok
python_tests.load_map_test.test_broken_files('../data/broken_maps/style_name_missing.xml',) ... ok
python_tests.load_map_test.test_broken_files('../data/broken_maps/font_name_broken.xml',) ... ok
python_tests.load_map_test.test_broken_files('../data/broken_maps/bgcolor_broken.xml',) ... ok
python_tests.load_map_test.test_broken_files('../data/broken_maps/bool_value_broken.xml',) ... ok
python_tests.load_map_test.test_broken_files('../data/broken_maps/missing_icon.xml',) ... ok
python_tests.load_map_test.test_broken_files('../data/broken_maps/db_host_broken.xml',) ... ok
python_tests.load_map_test.test_broken_files('../data/broken_maps/xml_tag_mismatch.xml',) ... ok
python_tests.load_map_test.test_broken_files('../data/broken_maps/css_value_broken.xml',) ... ok
python_tests.load_map_test.test_broken_files('../data/broken_maps/mapnik_min_version.xml',) ... ok
python_tests.load_map_test.test_broken_files('../data/broken_maps/line_join_style_broken.xml',) ... ok
python_tests.load_map_test.test_broken_files('../data/broken_maps/expression_broken.xml',) ... ok
python_tests.load_map_test.test_broken_files('../data/broken_maps/amenity.xml',) ... ok
python_tests.load_map_test.test_broken_files('../data/broken_maps/text_symbolizer_broken.xml',) ... ok
python_tests.load_map_test.test_broken_files('../data/broken_maps/line_pattern_symbolizer_broken.xml',) ... ok
python_tests.load_map_test.test_broken_files('../data/broken_maps/polygon_pattern_symbolizer_broken.xml',) ... ok
python_tests.load_map_test.test_broken_files('../data/broken_maps/line_cap_style_broken.xml',) ... ok
python_tests.load_map_test.test_broken_files('../data/broken_maps/max_scale_denom_broken.xml',) ... ok
python_tests.load_map_test.test_broken_files('../data/broken_maps/shield_symbolizer_broken.xml',) ... ok
python_tests.load_map_test.test_broken_files('../data/broken_maps/min_scale_denom_broken.xml',) ... ok
python_tests.load_map_test.test_broken_files('../data/broken_maps/datasource_type_broken.xml',) ... ok
python_tests.load_map_test.test_broken_files('../data/broken/does_not_exist.xml',) ... ok
python_tests.load_map_test.test_good_files('../data/good_maps/bool_values.xml',) ... ok
python_tests.load_map_test.test_good_files('../data/good_maps/osm-styles.xml',) ... ok
python_tests.load_map_test.test_good_files('../data/good_maps/whitespace_at_end_of_filter_expression.xml',) ... ok
python_tests.load_map_test.test_good_files('../data/good_maps/filesource.xml',) ... ok
python_tests.load_map_test.test_good_files('../data/good_maps/unique_filter_map.xml',) ... ok
python_tests.load_map_test.test_good_files('../data/good_maps/datasource.xml',) ... ok
python_tests.load_map_test.test_good_files('../data/good_maps/agg_poly_gamma_map.xml',) ... ok
python_tests.load_map_test.test_good_files('../data/good_maps/building_symbolizer.xml',) ... ok
python_tests.load_map_test.test_good_files('../data/good_maps/oblique_or_italic_fonts.xml',) ... ok
python_tests.load_map_test.test_good_files('../data/good_maps/paths_relative_to_script.xml',) ... ok
python_tests.load_map_test.test_good_files('../data/good_maps/point_symbolizer_on_polygon_map.xml',) ... ok
python_tests.load_map_test.test_good_files('../data/good_maps/polygon_symbolizer.xml',) ... ok
python_tests.load_map_test.test_good_files('../data/good_maps/paths_relative_to_xml.xml',) ... ok
python_tests.load_map_test.test_good_files('../data/good_maps/mapnik_min_version.xml',) ... ok
python_tests.load_map_test.test_good_files('../data/good_maps/point_symbolizer.xml',) ... ok
python_tests.load_map_test.test_good_files('../data/good_maps/entities.xml',) ... ok
python_tests.object_test.test_shieldsymbolizer_init ... ok
python_tests.object_test.test_shieldsymbolizer_missing_image ... ok
python_tests.object_test.test_pointsymbolizer_init ... ok
python_tests.object_test.test_pointsymbolizer_missing_image ... ok
python_tests.object_test.test_pointsymbolizer_pickle ... ok
python_tests.object_test.test_polygonsymbolizer_init ... ok
python_tests.object_test.test_polygonsymbolizer_pickle ... ok
python_tests.object_test.test_stroke_init ... ok
python_tests.object_test.test_stroke_dash_arrays ... ok
python_tests.object_test.test_stroke_pickle ... ok
python_tests.object_test.test_linesymbolizer_init ... ok
python_tests.object_test.test_linesymbolizer_pickle ... ok
python_tests.object_test.test_shapefile_init ... ok
python_tests.object_test.test_shapefile_properties ... ok
python_tests.object_test.test_textsymbolizer_init ... ok
python_tests.object_test.test_textsymbolizer_pickle ... TODO: FontSet pickling support needed: http://trac.mapnik.org/ticket/348
python_tests.object_test.test_map_init ... ok
python_tests.object_test.test_map_init_from_string ... TODO: Need to write more map property tests in 'object_test.py'...
python_tests.object_test.test_map_pickle ... TODO: Map does not support pickling yet (Tickets #345).
python_tests.object_test.test_color_init ... ok
python_tests.object_test.test_color_equality ... ok
python_tests.object_test.test_color_pickle ... ok
python_tests.object_test.test_rule_init ... ok
python_tests.object_test.test_coord_init ... ok
python_tests.object_test.test_coord_multiplication ... ok
python_tests.object_test.test_envelope_init ... ok
python_tests.object_test.test_envelope_pickle ... ok
python_tests.object_test.test_envelope_multiplication ... ok
python_tests.projection_test.test_wgs84_inverse_forward ... ok
python_tests.render_test.test_simplest_render ... ok
python_tests.render_test.test_render_image_to_string ... ok
python_tests.render_test.test_render_image_to_file ... ok
python_tests.render_test.test_render_from_serialization ... ok
python_tests.render_test.test_render_points ... TODO: See: http://trac.mapnik.org/ticket/402
python_tests.save_map_test.test ... ok

---

Ran 84 tests in 0.283s

OK (TODO=5)
mats@ubuntu:~/mapnik$
